** Show mountains and mist

** Show Amalia's mask over mist

My name is Amalia.

** Pan downward from tree to soul procession of monks at bottom

I am the Spirit who lives in the White Cypress.
Like those who dwelt therein before, 
I guide the souls of Ildran 
as they pass between worlds.

** Mountains

I will tell thee now 
of an Age whose very stones have vanished,
so long ago began 
this tapestry of Sorrows.

** Smoky ellipsoid sun

When ash and smoke concealed 
the fury of the Sun,

** Gravestones

When famine and despair
swept through Ildran,

** Darkness w/suggestions of souls

When the Cypress died, 
leaving souls to roam in Shadow,

When a man of humility,
with little more than robe and longbow, passed
into the history of Heroes.

----- pause as brief title/credits sequence is shown -----

Not for Heroes
nor for wicked men,
can I reveal to thee
the destinies of Souls.

But of one blackened Soul, 
a malevolent Shade,
a Spirit most hateful and grim,
a designer of plagues,
and of vicious torments,

of this One,
I shall divulge, to thee,
a little more.

For though he vanished long before the birth of Sol,
His crimes will echo into Eternity.








 





