* Overview

** Player controls an unnamed monk in several randomly varying quests
** Several things to do on your way, which vary
** Optional things
** Ranged combat with bow-and-arrow
** Melee combat with fists/feet
** Magic spells
*** All spells require Mind points
*** Some spells require "reagents" i.e. a supply
** Manage limited resources: food, arrows, items/reagents
** Each quest is composed of your movements on the square sectors of a randomly generated worldmap
** When you move into a sector you get a randomly generated level in the sector's style
** Exploration and nonlinearity in what you gather/fight and in which order you visit squares
** Permadeath
** Story is exposed through the notebook, written letters/scrolls, NPC conversations, and the Astral Body spell
** Story pieces are randomly chosen (somewhat akin to special events or "vaults" in a roguelike)
** Crime investigation tasks

* Graphical presentation

All objects, evironments, and animation frames are individually
painted with acrylic artist paints on watercolor paper, and then
digitally composited and animated.

The game's world is shown from an overhead 2-D perspective. The world
view is full-frame, except for a thin black bar across the bottom
called the "modeline". This line is used for status display,
inventory, and menu. It is mostly unobtrusive, displaying the meter
bars for Body (Red) and Mind (Blue), and an icon for the currently
equipped item. Status icons and some other messages will also be
displayed here. The various meters and items can briefly blink when
something requires the player's attention, such as low health or a
poisoning event.

In-game text is rendered using an appropriate TrueType font. 

* Movement and combat

The monk's primary means of attack is the bow and arrow with which all
monks of the Order must acquire proficiency. Unarmed combat is less
powerful, but still useful at times.

* Player characteristics

** Body (0-100) (permadeath at 0)
** Mind (0-100) (used for casting spells. cannot cast anything when less than 15%)
** Hunger (0-100)
** Sleep (0-100)
** Cold (0-100)
** Poison (0-100)

* Controls

** Move with the arrow keys or numeric keypad
** Press SHIFT use the equipped weapon, item, or spell
** Press SPACEBAR (or "X") to pick up object / perform location-specific action
** Press ENTER (or "Z") to enter the menu and select menu options
** Control-S to swap Z and X buttons
** Use the arrow keys or numeric keypad to move the menu cursor 
** Press ESCAPE (or BACKSPACE or DEL) to quit the current menu

* Music and sound

The fantasy soundtrack employs FM synthesis and sampling to create
abstract, synthetic timbres. The sounds and melodies are meant to
evoke various archaic instruments and vocal styles. Music does not
loop in the game; most of the soundtrack's cues are short (about one
minute in length) and play once through when triggered by an event or
situation.  My overall aim is to create the musical atmosphere in
which an order of spiritual warrior-monks utilize music for a variety
of religious purposes, and also incidental and improvised music played
while traveling long distances.

* Magic spells / commands
** Spark (light torches, campfires, and dry out even soaked wood)
** Radiance (required for dark areas. needs one white or yellow flower.)
*** can only use crossbow in dark when not using torch
** Flame (fire attack)
** Cure light wounds (consumes beef jerky for greater healing)
** Wood sprite (shakes firewood off of trees and brings it to you)
** Reclaim (turns garbage and other debris into reagents
** Temporal Seance (see the past. requires Forget-me-nots)
** Astral Body (must be cast under bright moonlight)
** Translation
** Boil grasses (make small amounts of thin gruel. requires wild grasses and water)
** Leave area
** Flee
** Hold creature

* Items
** Arrows (craft from stone chips and wood)
** Torch (crafted from wood)
*** torch cannot be used simultaneously with bow
** Bundles of arrows (20 per)
** Water 
** White bread
** Wheat bread
** Beef jerky
** Notebook
** Forget-me-nots
** Snowdrop
** Wild violet
** Stones, stone chips
** Branches, wood planks, ruined wood
** Temple Incense

* Characters
** Unnamed Monk (the player)
** Geoffrey
** Francis
** Ian
** Dr. Quine
** good Rangers
** evil Brigands
** Imperial Raven
** Skeleton wanderer
** Skeleton soldier
** Soulless wolves
** Cryptghast
** Thief
** Skullscraper
** Eldritch acid pool
** Maggot hound
** Watcher-in-the-weeds
** Goddess 

* Locations
** Gleyborough
** Valisade
** Mountain pass
** Snowy glen
** Frozen river crossing
** Meadow
** Caves
** Abandoned village (optionally with tombstones and lurking undead)
** Forgotten cemetery
** Dungeon, castle ruins
** Ancient roadway
** Skeleton hideout

